# Generated by Django 5.0.14 on 2026-08-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exceeded', 'Exceeded')], default='active', max_length=15),
        ),
    ]
